### PR TITLE
Feat/image upload

### PR DESCRIPTION
**Pull request by nrobert**
Implementation of #21 : send file for Computer Vision, Custom Vision and Face demos:

image

Additional improvements:
- package updages
- cleanup: removed REST API Calls for Computer Vision Read V3 as it is now included in the Nuget Package

### CODE REVIEW

**Comment by PeterOrneholm** [comment]
Sorry for the delay on this. I've fixed the pull request build pipeline now.
Can you resolve the merge conflicts above and I'll make sure to get this into master.

**Comment by PeterOrneholm** [comment]
SOrry for the delayon this. I've fixed the pull request build pipeline now.
Can you resolve the merge conflicts above and I'll make sure to get this into master.

**Comment by nrobert** [comment]
Sure I will have a look on this soon

**Comment by nrobert** [comment]
Rebasing this feature branch on current master and fixing conflicts.

**Comment by PeterOrneholm** [comment]
Great work on this @nrobert :) I've already had use for it!

**Comment by nrobert** [comment]
Thanks @PeterOrneholm. That was an important step also from my point of view, I often want to directly send local images :)

**Pull request merged**
