### PR TITLE
Feature: Computer Vision Read operation from 3.0 API

### PR DESCRIPTION
**Pull request by nrobert**
Implementation of #16 

Additional details:

- Information of future depreciation of RecognizeText operation by Microsoft
- Specification of origin of operation in display (Nuget + implicit API call behind vs direct API)
- models organization in folders
- packages upgrade

### CODE REVIEW

**Comment by PeterOrneholm** [comment]
Thanks @nrobert! Will try to look at it during the week.

**Comment by nrobert** [comment]
Hi Peter, just an additional point regarding the content on Computer Vision: for the text processing operations, we will have after this PR the following possibilities:
- Recognize Text (using Nuget package - 2.1 API): asynchronous, and will be deprecated (from 3.0 version of the API) in favor of Read
- Batch Read (using Nuget package - 2.1 API): asynchronous, has evolved as Read in 3.0 API
- Read (using 3.0 API): asynchronous, corresponding to the latest evolution
- OCR (using Nuget package - 2.1 API): synchronous and still existing in 3.0 API

=> I guess we should limit the calls to Read and OCR soon. Currently I added all the possibilities in order to be able to compare, and due to the fact that current Nuget package is still pointing to 2.1 API

**Comment by nrobert** [comment]
@PeterOrneholm , if you can have a look to this PR that would be cool because 2.0 RecognizeText operation will be removed in the near future (like November 16)

**Comment by PeterOrneholm** [comment]
Really sorry for the delay on this one. Thanks for great work!

Code looks fine, but a few feedbacks.

1. Do we really need to keep _Recognize Text_ and _Batch read_? OCR supports more languages, but I'd like to go with just _Read_ and OCR.
2. I'd like to avoid the "comments" in the headers, like _(using Nuget: API 2.1)_ It adds noice. If necessary, I'd like to see them as "Secondary texts" n Bootstrap (https://getbootstrap.com/docs/4.5/content/typography/#customizing-headings).
3. In master I merged the two properties relevant for OCR into one line to make the "settings" pane a little shorter. I think it was split into multiple lines now. See image below:

image

**Comment by nrobert** [comment]
Hi Peter,

I will have a look to the feedbacks.

1. Since the creation of the release, the depreciation timeline of OCR methods is a lot clearer. Based on the communications I received, I think keeping OCR and Read is the right solution yes. I will edit the PR.
2. Secondary texts looks fine. The idea of these comments was to explain to devs how the solution is used, as there are now many ways and versions of the API / Nuget packages
3. Ok, having 3 ways of doing OCR was causing display issues for a single line. But if we remove "Recognize Text" that will be fine.

I will do these changes in the next hours / days.

**Comment by nrobert** [comment]
Another point about parameters: shouldn't we put the image URL field at the beginning of the parameter? That's maybe the most important one

**Comment by PeterOrneholm** [comment]
> I will do these changes in the next hours / days.

Great!



> Another point about parameters: shouldn't we put the image URL field at the beginning of the parameter? That's maybe the most important one

I agree! Can you swap it?

**Comment by nrobert** [comment]
@PeterOrneholm , changes done.

- RecognizeText removed
- Batch Read removed
- Image URL parameter put on top for all tabs
- 2 "text recognition methods" parameters grouped in 1 line (1 used for OCR operation, 1 for Read operation)
- Packages upgrades for ComputerVision, Face, CustomVision (all project packages are up-to-date)

**Comment by PeterOrneholm** [comment]
Looks great, thanks! I think the failing pipeline is due to wrong access rights. I'll merge and give it a try.

**Comment by nrobert** [comment]
The release is ok on your website, the changes are deployed and my tests are ok.

**Pull request merged**
